# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Masterwork Code 
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
        This is my website. A place where you can see updates for all of my
        current projects. I program mainly in C and C++ and would love to help
        people for all of their programming needs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.masterwork-code.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username: mckinneyaa 

# Build settings
markdown: kramdown
